version: "3.8"
services:
  bot:
    image: ghcr.io/octo-tg-bot/octotgbot:latest
    volumes:
      - ./settings.toml:/app/settings.toml
      - ./preimport.py:/app/preimport.py
    links:
      - redis
    environment:
      ob_redis: '{"host": "redis", "port": 6379, "db": 0}'
    labels:
      - "com.centurylinklabs.watchtower.scope=octobot"
    depends_on: 
      - redis
    restart_policy:
      condition: on-failure
  redis:
    image: redis:6-alpine
    command: redis-server --appendonly yes
    volumes:
      - ob_redisvolume:/data
    restart_policy:
      condition: on-failure
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --interval 30 --scope octobot
    labels:
      - "com.centurylinklabs.watchtower.scope=octobot"
volumes:
  ob_redisvolume:
