version: "2.4"
services:
  bot:
    image: docker.pkg.github.com/octo-tg-bot/octobotv4/octotgbot:latest
    volumes:
      - ./settings.toml:/app/settings.toml
      - ./preimport.py:/app/preimport.py
    links:
      - redis
    environment:
      ob_redis: '{"host": "redis", "port": 6379, "db": 0}'
    labels:
      - "com.centurylinklabs.watchtower.scope=octobot"
  redis:
    image: redis:6-alpine
    command: redis-server --appendonly yes
    volumes:
      - ob_redisvolume:/data
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --interval 30 --scope octobot
    labels:
      - "com.centurylinklabs.watchtower.scope=octobot"
volumes:
  ob_redisvolume:
